---
gpu_packages:
  - mesa
  - lib32-mesa
  - xf86-video-amdgpu
  - vulkan-radeon
  - vulkan-headers
  - lib32-vulkan-radeon
  - amdvlk
  - lib32-amdvlk
  - libva-mesa-driver
  - lib32-libva-mesa-driver
  - mesa-vdpau
  - lib32-mesa-vdpau
